// <auto-generated />
namespace AesophWorks.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class attributecolumnadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(attributecolumnadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202204292347202_attributecolumnadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
